### ISSUE TITLE
Validator: Initial implementation

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-toolbox-php#194]
The AMP Toolbox should have a full PHP implementation of the AMP validator

- [ ] Generate PHP representation of validator spec => #100 
- [ ] Implement validators that pass or fail validator spec rules
- [ ] Hook up https://github.com/ampproject/amphtml/tree/main/validator/testdata to verify parity with upstream
- [ ] Build CLI command to validate a URL or a piece of markup

**Comment by westonruter** [comment]
Interesting. The JavaScript implementation of the validator is being deprecated in favor of a WASM version which reuses the C++ implementation: https://github.com/ampproject/amphtml/issues/36110

**Comment by schlessera** [comment]
Nice, now that I've ported the JS HTML Parser... :/

I'll go through the C++ code to see what needs adapting then.

**Comment by westonruter** [comment]
I believe they have had feature parity until now, so hopefully there's nothing that needs to change.
