### ISSUE TITLE
Release checklist for v1.0.0

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-toolbox-php#34]
The following is a list of tasks/issues we need to complete for a feature-complete v1.0.0 release of the optimizer.

- [ ] New Transformer: BrowserHints [[#31](https://github.com/ampproject/amp-toolbox-php/issues/31)]
- [ ] New Transformer: AutoExtensions [[#32](https://github.com/ampproject/amp-toolbox-php/issues/32)]
- [ ] Copy object-position & object-fit into style attribute to reduce LCP [[#6](https://github.com/ampproject/amp-toolbox-php/issues/6)]
- [ ] Server-side rendering can cause style[amp-custom] CSS overage [[#19](https://github.com/ampproject/amp-toolbox-php/issues/19)]
- [ ] Support unit-based width/height attributes in ImageDimensions [[#4](https://github.com/ampproject/amp-toolbox-php/issues/4)]
- [ ] Add PHP Optimizer guide to amp.dev [[#33](https://github.com/ampproject/amp-toolbox-php/issues/33)]

**Comment by jwold** [comment]
AS > 

The idea was to have 1.0 feature complete with validator and sanitizer; but for 2.2 it's too ambitious, and we will require this to be ready for 2.3. A lot of work has been done, but it will not be finished for 2.2 release. Alain will update this issue, the issue as it's written for 1.0 being feature complete for optimizer only.

But we discussed for 1.0 release to have a launch with buzz, where we are feature complete for entire AMP tooling, not only optimizer. That would be sanitizer + validator + optimizer. Optimizer mostly done, validator in progress, and sanitizer is easiest to port. 

As it is being completely fulfilled by plugin least priority.
